version: 2.1

executors:
  default:
    docker:
      - image: circleci/python@0.2.1
  
jobs:    

  publish_to_pypi:
    executor: default

    steps:
      - checkout
      - run:
          name: "switch keys and check out client repo"
          command: |
            sudo pip3 install --upgrade pip
            sudo pip3 install flit
            sudo pip3 install pygments
            flit install --deps none
            flit build
            flit publish

workflows:

  on_commit:
    jobs:
      - publish_to_pypi:
          context: python_client_publish
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
