version: 2

jobs:
    - toxify:
        context: aqua-test
        docker:
            - image: themattrix/tox
        
        steps:
            - checkout
            - run: tox
    - pep8:
        docker:
            - image: themattrix/tox
        steps:
            - checkout
            - run: pip install pep8
            - run: pep8 --config=pep8.cfg . --exclude=platform_client_server_utils,qcware/params_pb2.py,./build/lib/qcware/params_pb2.py
        
