version: 2

jobs:

  just_checkout:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
  
  toxify:
    docker:
      - image: themattrix/tox
        
    steps:
      - checkout
      - run: tox

workflows:
  version: 2
  run-tests:
    jobs:
      - just_checkout
#      - toxify:
#          context: aqua_client
#      - pep8
