version: 2

jobs:
  toxify:
    docker:
      - image: themattrix/tox
        
    steps:
      - checkout
      - run: tox

  pep8:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run: pip install --user pycodestyle
      - run: ~/.local/bin/pycodestyle --config=pycodestyle.cfg . --exclude=platform_client_server_utils,qcware/params_pb2.py,./build/lib/qcware/params_pb2.py

workflows:
  version: 2
#  run-tests:
#    jobs:
#      - toxify:
#          context: aqua_client
#      - pep8
